#ifndef __AIRPORTDATA_H__
#define __AIRPORTDATA_H__
#include <map>
#include <string>
#include "airportstruct.h"
// Handy file for keeping your airport codes in.

std::map<std::string, airport_t> airportMapping = {
    {"CTCK", {"CTCK", 0, "NONE"}},
    {"CTNK", {"CTNK", 1, "NONE"}},
    {"CTRA", {"CTRA", 2, "NONE"}},
    {"CWAJ", {"CWAJ", 3, "NONE"}},
    {"CWCI", {"CWCI", 4, "NONE"}},
    {"CWCJ", {"CWCJ", 7, "NONE"}},
    {"CWCO", {"CWCO", 8, "NONE"}},
    {"CWDV", {"CWDV", 9, "NONE"}},
    {"CWGD", {"CWGD", 10, "NONE"}},
    {"CWGH", {"CWGH", 11, "NONE"}},
    {"CWGL", {"CWGL", 12, "NONE"}},
    {"CWKK", {"CWKK", 13, "NONE"}},
    {"CWLS", {"CWLS", 14, "NONE"}},
    {"CWMZ", {"CWMZ", 15, "NONE"}},
    {"CWNC", {"CWNC", 16, "NONE"}},
    {"CWNZ", {"CWNZ", 17, "NONE"}},
    {"CWPC", {"CWPC", 18, "NONE"}},
    {"CWQP", {"CWQP", 19, "NONE"}},
    {"CWRK", {"CWRK", 20, "NONE"}},
    {"CWWB", {"CWWB", 21, "NONE"}},
    {"CWWZ", {"CWWZ", 22, "NONE"}},
    {"CXBI", {"CXBI", 23, "NONE"}},
    {"CXCA", {"CXCA", 24, "NONE"}},
    {"CXDI", {"CXDI", 25, "NONE"}},
    {"CXEA", {"CXEA", 26, "NONE"}},
    {"CXET", {"CXET", 27, "NONE"}},
    {"CXHA", {"CXHA", 28, "NONE"}},
    {"CXHM", {"CXHM", 29, "NONE"}},
    {"CXKA", {"CXKA", 30, "NONE"}},
    {"CXKE", {"CXKE", 31, "NONE"}},
    {"CXKI", {"CXKI", 32, "NONE"}},
    {"CXPC", {"CXPC", 33, "NONE"}},
    {"CXTO", {"CXTO", 34, "NONE"}},
    {"CXVN", {"CXVN", 35, "NONE"}},
    {"CXZC", {"CXZC", 36, "NONE"}},
    {"CYAM", {"CYAM", 37, "NONE"}},
    {"CYAT", {"CYAT", 38, "NONE"}},
    {"CYCK", {"CYCK", 39, "NONE"}},
    {"CYER", {"CYER", 40, "NONE"}},
    {"CYGK", {"CYGK", 41, "NONE"}},
    {"CYHD", {"CYHD", 42, "NONE"}},
    {"CYHM", {"CYHM", 43, "NONE"}},
    {"CYKF", {"CYKF", 44, "NONE"}},
    {"CYKP", {"CYKP", 45, "NONE"}},
    {"CYLD", {"CYLD", 46, "NONE"}},
    {"CYLH", {"CYLH", 47, "NONE"}},
    {"CYMO", {"CYMO", 48, "NONE"}},
    {"CYOO", {"CYOO", 49, "NONE"}},
    {"CYOW", {"CYOW", 50, "NONE"}},
    {"CYPO", {"CYPO", 51, "NONE"}},
    {"CYPQ", {"CYPQ", 52, "NONE"}},
    {"CYQA", {"CYQA", 53, "NONE"}},
    {"CYQG", {"CYQG", 54, "NONE"}},
    {"CYQK", {"CYQK", 55, "NONE"}},
    {"CYQT", {"CYQT", 56, "NONE"}},
    {"CYRL", {"CYRL", 57, "NONE"}},
    {"CYSB", {"CYSB", 58, "NONE"}},
    {"CYSN", {"CYSN", 59, "NONE"}},
    {"CYSP", {"CYSP", 60, "NONE"}},
    {"CYTL", {"CYTL", 61, "NONE"}},
    {"CYTR", {"CYTR", 62, "NONE"}},
    {"CYTS", {"CYTS", 63, "NONE"}},
    {"CYTZ", {"CYTZ", 64, "NONE"}},
    {"CYVV", {"CYVV", 65, "NONE"}},
    {"CYXL", {"CYXL", 66, "NONE"}},
    {"CYXR", {"CYXR", 67, "NONE"}},
    {"CYXU", {"CYXU", 68, "NONE"}},
    {"CYXZ", {"CYXZ", 69, "NONE"}},
    {"CYYB", {"CYYB", 70, "NONE"}},
    {"CYYU", {"CYYU", 71, "NONE"}},
    {"CYYW", {"CYYW", 72, "NONE"}},
    {"CYYZ", {"CYYZ", 73, "NONE"}},
    {"CYZE", {"CYZE", 74, "NONE"}},
    {"CYZR", {"CYZR", 75, "NONE"}},
    {"CZEL", {"CZEL", 76, "NONE"}},
    {"CZMD", {"CZMD", 77, "NONE"}},
    {"CZSJ", {"CZSJ", 78, "NONE"}},
    {"CZTB", {"CZSJ", 79, "NONE"}}};
#endif //__AIRPORTDATA_H__